### ISSUE TITLE
How to use with releases?

### ISSUE THREAD

**Issue by ostinelli** [ostinelli/rebar3_vendor#2]
Hi Tristan,
I'm moving from rebar2 to rebar3 in a production project.

I've vendored my dependencies with this plugin:

```
$ rebar3 vendor store
$ find deps/ -name ".git" | xargs rm -rf
```

In the second line I remove `.git` directories as the whole purpose of this is to be able to commit dependencies.

When I want to release:

```
$ rebar3 vendor apply
$ rebar3 as prod tar
```

However I get:

```
$ make release
===> Applying vendored dependencies...
===> Verifying dependencies...
===> Upgrading cowbell ({git,"git://github.com/ostinelli/cowbell.git",
                                   {ref,
                                       "c3193d233b085b3971706f1bac71d3ba84401936"}})

[...]
```

Why is there an upgrade? I don't want rebar3 to fetch dependencies, just use the ones that are included in the project.

Is this because the `.git` directories are not included anymore?

I also tried:

```
$ rebar3 as prod vendor apply
$ rebar3 as prod tar
```

and

```
$ rebar3 vendor apply
$ rebar3 as prod vendor apply
$ rebar3 as prod tar
```

The behaviour is the same.

Any pointers are appreciated. ^^_

**Comment by tsloughter** [comment]
Yea, it is because you removed the git directories. If you use git dependencies you have to keep that or else rebar3 thinks you don't actually have the correct dependency, and it won't take your word for it.

**Comment by ostinelli** [comment]
Ok, however the whole point is to commit the dependencies too. A possible solution is to zip all the dependencies - 1 .zip file per dependency (including the `.git` directories) during the `store`, and unzip them during the `apply`.

What do you think?

**Comment by ostinelli** [comment]
I've created a [pull request for this](https://github.com/tsloughter/rebar3_vendor/pull/3).

What this does:
- `store` will create all zipped files inside of the `deps` directory, such as `mydep-1.2.3.zip`.
- `apply` will unzip the zipped dependencies back where they belong.

This solves committing dependencies while keeping the `.git` directories so that everything works fine.

**Comment by ostinelli** [comment]
Thank you for merging in, Tristan.
Do you have an estimate when this is going to be in a 0.2.0 on hex?

**Comment by tsloughter** [comment]
I can publish 0.2.0 today. I'll ping you here when I do.

**Comment by ostinelli** [comment]
Awesome.

**Comment by tsloughter** [comment]
Published.
